export type FieldTag = 'pii' | 'identifier' | 'financial' | 'risk' | 'behavioral' | 'network' | 'temporal'

export interface FieldDef {
  name: string
  type: string
  tag: FieldTag
  joinKey?: boolean
  description: string
}

export interface TableDef {
  id: string
  label: string
  description: string
  recordCount: number
  fields: FieldDef[]
}

export interface JoinKey {
  id: string
  category: 'hard' | 'soft' | 'behavioral'
  leftTable: string
  leftField: string
  rightTable: string
  rightField: string
  signal: string
  confidence: number
  description: string
}

export const TAG_COLORS: Record<FieldTag, { bg: string; text: string; label: string }> = {
  pii:        { bg: 'bg-rose-50',   text: 'text-rose-700',   label: 'PII' },
  identifier: { bg: 'bg-indigo-50', text: 'text-indigo-700', label: 'ID' },
  financial:  { bg: 'bg-emerald-50',text: 'text-emerald-700',label: 'FIN' },
  risk:       { bg: 'bg-amber-50',  text: 'text-amber-700',  label: 'RISK' },
  behavioral: { bg: 'bg-purple-50', text: 'text-purple-700', label: 'BEHAV' },
  network:    { bg: 'bg-sky-50',    text: 'text-sky-700',    label: 'NET' },
  temporal:   { bg: 'bg-slate-100', text: 'text-slate-600',  label: 'TIME' },
}

export const CAP_SCHEMA: TableDef[] = [
  {
    id: 'cap_customers',
    label: 'cap_customers',
    description: 'Core CRM — one row per cardholder identity',
    recordCount: 5000,
    fields: [
      { name: 'customer_id',       type: 'varchar',   tag: 'identifier', joinKey: true,  description: 'Primary key — CAP-XXXXXX format' },
      { name: 'first_name',        type: 'varchar',   tag: 'pii',        joinKey: true,  description: 'Given name' },
      { name: 'last_name',         type: 'varchar',   tag: 'pii',        joinKey: true,  description: 'Family name' },
      { name: 'name_hash',         type: 'varchar',   tag: 'identifier', joinKey: true,  description: 'SHA-256 of normalized full name — fuzzy ER key' },
      { name: 'ssn_last4',         type: 'char(4)',   tag: 'pii',        joinKey: true,  description: 'Last 4 of SSN — high-confidence ER signal' },
      { name: 'dob',               type: 'date',      tag: 'pii',        joinKey: true,  description: 'Date of birth — ER signal' },
      { name: 'email',             type: 'varchar',   tag: 'pii',        joinKey: true,  description: 'Primary email — fuzzy ER signal' },
      { name: 'phone_primary',     type: 'varchar',   tag: 'pii',        joinKey: true,  description: 'Primary phone — ER signal' },
      { name: 'phone_secondary',   type: 'varchar',   tag: 'pii',                       description: 'Secondary phone' },
      { name: 'address_billing',   type: 'varchar',   tag: 'pii',        joinKey: true,  description: 'Billing address line — fuzzy ER signal' },
      { name: 'address_mailing',   type: 'varchar',   tag: 'pii',                       description: 'Mailing address' },
      { name: 'city',              type: 'varchar',   tag: 'pii',                       description: 'City' },
      { name: 'state',             type: 'char(2)',   tag: 'pii',                       description: 'State code' },
      { name: 'zip',               type: 'char(5)',   tag: 'pii',                       description: 'ZIP code' },
      { name: 'kyc_status',        type: 'enum',      tag: 'risk',                      description: 'KYC verification status' },
      { name: 'kyc_tier',          type: 'int',       tag: 'risk',                      description: 'KYC tier 1–3' },
      { name: 'id_document_type',  type: 'enum',      tag: 'risk',                      description: 'Type of ID submitted at onboarding' },
      { name: 'acquisition_channel',type:'enum',      tag: 'behavioral',                description: 'How the customer was acquired' },
      { name: 'created_date',      type: 'date',      tag: 'temporal',                  description: 'Account creation date' },
    ],
  },
  {
    id: 'cap_accounts',
    label: 'cap_accounts',
    description: 'One row per card/loan account — linked to customer',
    recordCount: 5800,
    fields: [
      { name: 'account_id',         type: 'varchar',  tag: 'identifier',                description: 'Primary key' },
      { name: 'customer_id',        type: 'varchar',  tag: 'identifier',                description: 'FK → cap_customers' },
      { name: 'pan_hash',           type: 'varchar',  tag: 'identifier', joinKey: true, description: 'SHA-256 of PAN — hard join with network txns' },
      { name: 'bin',                type: 'char(6)',  tag: 'identifier', joinKey: true, description: 'Bank Identification Number — maps to BIN table' },
      { name: 'card_type',          type: 'enum',     tag: 'financial',  joinKey: true, description: 'consumer / commercial / secured — source of truth for card classification' },
      { name: 'product_code',       type: 'varchar',  tag: 'identifier',                description: 'Product SKU' },
      { name: 'credit_limit',       type: 'decimal',  tag: 'financial',                 description: 'Approved credit line' },
      { name: 'current_balance',    type: 'decimal',  tag: 'financial',                 description: 'Outstanding balance' },
      { name: 'risk_grade',         type: 'enum',     tag: 'risk',                      description: 'A–F internal risk grade' },
      { name: 'behavior_score',     type: 'int',      tag: 'risk',                      description: 'Proprietary behavioral score 0–999' },
      { name: 'fico_at_origination',type: 'int',      tag: 'risk',                      description: 'FICO at account opening' },
      { name: 'delinquency_status', type: 'enum',     tag: 'risk',                      description: 'Current / 30DPD / 60DPD / 90DPD / charge-off' },
      { name: 'days_past_due',      type: 'int',      tag: 'risk',                      description: 'Days past due' },
      { name: 'opened_date',        type: 'date',     tag: 'temporal',                  description: 'Account open date' },
    ],
  },
  {
    id: 'cap_transactions',
    label: 'cap_transactions',
    description: 'Issuer authorization view — each purchase, decline, or ATM withdrawal',
    recordCount: 50000,
    fields: [
      { name: 'txn_id',              type: 'varchar', tag: 'identifier',                description: 'Primary key' },
      { name: 'account_id',          type: 'varchar', tag: 'identifier',                description: 'FK → cap_accounts' },
      { name: 'merchant_name_raw',   type: 'varchar', tag: 'network',                   description: 'Merchant name as received from network' },
      { name: 'merchant_id',         type: 'varchar', tag: 'identifier', joinKey: true, description: 'Discover MID — hard join key when routed on Discover network' },
      { name: 'mcc',                 type: 'char(4)', tag: 'network',                   description: 'Merchant Category Code' },
      { name: 'amount',              type: 'decimal', tag: 'financial',                 description: 'Transaction amount' },
      { name: 'currency',            type: 'char(3)', tag: 'financial',                 description: 'ISO 4217 currency' },
      { name: 'auth_code',           type: 'varchar', tag: 'identifier', joinKey: true, description: '6-char auth code — hard join to network_txn_id' },
      { name: 'auth_response_code',  type: 'char(2)', tag: 'network',                   description: '00=approved, 05=declined, 51=insufficient funds' },
      { name: 'txn_datetime',        type: 'timestamp',tag: 'temporal',                 description: 'Authorization timestamp' },
      { name: 'channel',             type: 'enum',    tag: 'behavioral',                description: 'POS / CNP / contactless / ATM' },
      { name: 'device_fingerprint',  type: 'varchar', tag: 'identifier', joinKey: true, description: 'Device hash — soft join to terminal device' },
      { name: 'ip_address',          type: 'varchar', tag: 'behavioral', joinKey: true, description: 'IP at time of auth — soft join to terminal IP' },
      { name: 'token_id',            type: 'varchar', tag: 'identifier',                description: 'Apple/Google Pay vault token' },
      { name: 'is_3ds_authenticated',type: 'boolean', tag: 'risk',                      description: '3D Secure authentication flag' },
    ],
  },
  {
    id: 'cap_device_sessions',
    label: 'cap_device_sessions',
    description: 'Login and app session telemetry per account',
    recordCount: 15000,
    fields: [
      { name: 'session_id',         type: 'varchar',   tag: 'identifier',               description: 'Primary key' },
      { name: 'account_id',         type: 'varchar',   tag: 'identifier',               description: 'FK → cap_accounts' },
      { name: 'device_fingerprint', type: 'varchar',   tag: 'identifier', joinKey: true,description: 'Device hash — soft join to terminal serial' },
      { name: 'device_type',        type: 'enum',      tag: 'behavioral',               description: 'mobile / desktop / tablet' },
      { name: 'os_version',         type: 'varchar',   tag: 'behavioral',               description: 'OS and version string' },
      { name: 'ip_address',         type: 'varchar',   tag: 'behavioral', joinKey: true,description: 'Session IP — soft join to terminal IP' },
      { name: 'ip_geo_city',        type: 'varchar',   tag: 'behavioral',               description: 'Geo-IP city' },
      { name: 'ip_geo_country',     type: 'char(2)',   tag: 'behavioral',               description: 'Geo-IP country' },
      { name: 'browser_fingerprint',type: 'varchar',   tag: 'identifier',               description: 'Browser canvas/JS fingerprint' },
      { name: 'user_agent',         type: 'varchar',   tag: 'behavioral',               description: 'User-Agent header' },
      { name: 'login_datetime',     type: 'timestamp', tag: 'temporal',                 description: 'Session start time' },
      { name: 'biometric_score',    type: 'decimal',   tag: 'risk',                     description: 'Behavioral biometric confidence 0–1' },
    ],
  },
  {
    id: 'cap_disputes',
    label: 'cap_disputes',
    description: 'Cardholder-initiated disputes and fraud claims',
    recordCount: 1500,
    fields: [
      { name: 'dispute_id',          type: 'varchar', tag: 'identifier',               description: 'Primary key' },
      { name: 'account_id',          type: 'varchar', tag: 'identifier',               description: 'FK → cap_accounts' },
      { name: 'txn_id',              type: 'varchar', tag: 'identifier', joinKey: true,description: 'FK → cap_transactions — joins to network chargeback' },
      { name: 'dispute_type',        type: 'enum',    tag: 'risk',                     description: 'fraud / unauthorized / quality' },
      { name: 'reason_code',         type: 'varchar', tag: 'risk',                     description: 'Network reason code (Visa/MC/Discover scheme)' },
      { name: 'claim_amount',        type: 'decimal', tag: 'financial',                description: 'Amount disputed' },
      { name: 'chargeback_initiated',type: 'boolean', tag: 'risk',                     description: 'Whether a chargeback was filed' },
      { name: 'resolution_status',   type: 'enum',    tag: 'risk',                     description: 'open / resolved_cardholder / resolved_merchant / withdrawn' },
      { name: 'resolution_date',     type: 'date',    tag: 'temporal',                 description: 'Date resolved — null if open' },
    ],
  },
  {
    id: 'cap_commercial',
    label: 'cap_commercial',
    description: 'Commercial banking counterparties and credit facilities',
    recordCount: 400,
    fields: [
      { name: 'counterparty_id',     type: 'varchar', tag: 'identifier',               description: 'Primary key' },
      { name: 'legal_name',          type: 'varchar', tag: 'pii',                      description: 'Legal entity name' },
      { name: 'dba_name',            type: 'varchar', tag: 'pii',        joinKey: true,description: 'DBA name — fuzzy join to merchant name' },
      { name: 'ein_hash',            type: 'varchar', tag: 'identifier', joinKey: true,description: 'EIN hash — hard join to merchant EIN' },
      { name: 'registration_state',  type: 'char(2)', tag: 'identifier',               description: 'State of incorporation' },
      { name: 'naics_code',          type: 'char(6)', tag: 'financial',                description: 'Industry classification' },
      { name: 'credit_facility_id',  type: 'varchar', tag: 'identifier',               description: 'Facility reference' },
      { name: 'exposure_amount',     type: 'decimal', tag: 'financial',                description: 'Total credit exposure' },
      { name: 'risk_rating',         type: 'enum',    tag: 'risk',                     description: 'investment_grade / speculative / distressed' },
      { name: 'covenant_status',     type: 'enum',    tag: 'risk',                     description: 'compliant / waiver / breach' },
      { name: 'last_review_date',    type: 'date',    tag: 'temporal',                 description: 'Last credit review date' },
      { name: 'beneficial_owner_ids',type: 'array',   tag: 'identifier', joinKey: true,description: 'Array of CAP customer IDs who own ≥25% — key NBFI link' },
    ],
  },
]

export const DISC_SCHEMA: TableDef[] = [
  {
    id: 'disc_customers',
    label: 'disc_customers',
    description: 'Discover\'s own cardholder CRM — the ER target',
    recordCount: 4000,
    fields: [
      { name: 'customer_id',        type: 'varchar',  tag: 'identifier',                description: 'Primary key — DIS-XXXXXX format' },
      { name: 'first_name',         type: 'varchar',  tag: 'pii',        joinKey: true, description: 'Given name' },
      { name: 'last_name',          type: 'varchar',  tag: 'pii',        joinKey: true, description: 'Family name — may have minor spelling variant' },
      { name: 'name_hash',          type: 'varchar',  tag: 'identifier', joinKey: true, description: 'SHA-256 of normalized name — Jaro-Winkler matched against cap_customers' },
      { name: 'ssn_last4',          type: 'char(4)',  tag: 'pii',        joinKey: true, description: 'Last 4 SSN — highest-confidence ER signal (35 pts)' },
      { name: 'dob',                type: 'date',     tag: 'pii',        joinKey: true, description: 'Date of birth — ER signal (25 pts)' },
      { name: 'email',              type: 'varchar',  tag: 'pii',        joinKey: true, description: 'Email — may differ from Cap One record' },
      { name: 'phone_primary',      type: 'varchar',  tag: 'pii',        joinKey: true, description: 'Primary phone — ER signal' },
      { name: 'address_billing',    type: 'varchar',  tag: 'pii',        joinKey: true, description: 'Billing address — fuzzy token match' },
      { name: 'city',               type: 'varchar',  tag: 'pii',                       description: 'City' },
      { name: 'state',              type: 'char(2)',  tag: 'pii',                       description: 'State code' },
      { name: 'zip',                type: 'char(5)',  tag: 'pii',                       description: 'ZIP code' },
      { name: 'kyc_status',         type: 'enum',     tag: 'risk',                      description: 'Discover\'s KYC verification status' },
      { name: 'acquisition_channel',type: 'enum',     tag: 'behavioral',                description: 'Customer acquisition channel' },
      { name: 'created_date',       type: 'date',     tag: 'temporal',                  description: 'Account creation date' },
      { name: 'cashback_enrolled',  type: 'boolean',  tag: 'behavioral',                description: 'Enrolled in Cashback Bonus program' },
    ],
  },
  {
    id: 'disc_accounts',
    label: 'disc_accounts',
    description: 'Discover product accounts — credit cards, loans, deposits',
    recordCount: 4500,
    fields: [
      { name: 'account_id',    type: 'varchar',  tag: 'identifier',               description: 'Primary key' },
      { name: 'customer_id',   type: 'varchar',  tag: 'identifier',               description: 'FK → disc_customers' },
      { name: 'pan_hash',      type: 'varchar',  tag: 'identifier', joinKey: true,description: 'PAN hash — hard join to network transactions' },
      { name: 'bin',           type: 'char(6)',  tag: 'identifier', joinKey: true,description: 'BIN — maps to disc_bin_table' },
      { name: 'product_type',  type: 'enum',     tag: 'financial',                description: 'credit_card / student_loan / personal_loan / savings / checking' },
      { name: 'product_code',  type: 'varchar',  tag: 'identifier',               description: 'Product SKU' },
      { name: 'credit_limit',  type: 'decimal',  tag: 'financial',                description: 'Credit line (null for non-revolving products)' },
      { name: 'current_balance',type:'decimal',  tag: 'financial',                description: 'Outstanding balance' },
      { name: 'apr',           type: 'decimal',  tag: 'financial',                description: 'Annual percentage rate' },
      { name: 'cashback_rate', type: 'decimal',  tag: 'financial',                description: 'Cashback reward rate' },
      { name: 'rewards_balance',type:'decimal',  tag: 'financial',                description: 'Accumulated cashback balance' },
      { name: 'status',        type: 'enum',     tag: 'risk',                     description: 'active / delinquent / closed' },
      { name: 'opened_date',   type: 'date',     tag: 'temporal',                 description: 'Account open date' },
    ],
  },
  {
    id: 'disc_cardholder_txns',
    label: 'disc_cardholder_txns',
    description: 'Discover cardholders\' own transactions — issuer view, enriched with network data',
    recordCount: 35000,
    fields: [
      { name: 'txn_id',          type: 'varchar',   tag: 'identifier',               description: 'Primary key' },
      { name: 'account_id',      type: 'varchar',   tag: 'identifier',               description: 'FK → disc_accounts' },
      { name: 'network_txn_id',  type: 'varchar',   tag: 'identifier', joinKey: true,description: 'FK → disc_network_txns — joins issuer and network views' },
      { name: 'merchant_id',     type: 'varchar',   tag: 'identifier', joinKey: true,description: 'FK → disc_merchants' },
      { name: 'amount',          type: 'decimal',   tag: 'financial',                description: 'Transaction amount' },
      { name: 'cashback_earned', type: 'decimal',   tag: 'financial',                description: 'Cashback earned on this transaction' },
      { name: 'txn_datetime',    type: 'timestamp', tag: 'temporal',                 description: 'Transaction timestamp' },
      { name: 'mcc',             type: 'char(4)',   tag: 'network',                  description: 'Merchant Category Code' },
      { name: 'channel',         type: 'enum',      tag: 'behavioral',               description: 'POS / CNP / contactless / ATM' },
      { name: 'status',          type: 'enum',      tag: 'risk',                     description: 'approved / declined / pending' },
    ],
  },
  {
    id: 'disc_merchants',
    label: 'disc_merchants',
    description: 'Merchant registry — every business accepting Discover network payments',
    recordCount: 2000,
    fields: [
      { name: 'merchant_id',       type: 'varchar', tag: 'identifier', joinKey: true,description: 'MID — hard join to cap_transactions.merchant_id' },
      { name: 'merchant_name',     type: 'varchar', tag: 'identifier',               description: 'Trading name' },
      { name: 'dba_name',          type: 'varchar', tag: 'identifier',               description: 'Doing-Business-As name' },
      { name: 'legal_entity_name', type: 'varchar', tag: 'identifier', joinKey: true,description: 'Legal name — fuzzy join to cap_commercial.legal_name' },
      { name: 'ein_hash',          type: 'varchar', tag: 'identifier', joinKey: true,description: 'EIN hash — hard join to cap_commercial.ein_hash' },
      { name: 'mcc',               type: 'char(4)', tag: 'network',                  description: 'Merchant Category Code' },
      { name: 'address_street',    type: 'varchar', tag: 'pii',                      description: 'Street address' },
      { name: 'address_city',      type: 'varchar', tag: 'pii',                      description: 'City' },
      { name: 'address_state',     type: 'char(2)', tag: 'pii',                      description: 'State' },
      { name: 'address_zip',       type: 'char(5)', tag: 'pii',                      description: 'ZIP' },
      { name: 'phone',             type: 'varchar', tag: 'pii',                      description: 'Merchant phone' },
      { name: 'email',             type: 'varchar', tag: 'pii',                      description: 'Merchant email' },
      { name: 'website',           type: 'varchar', tag: 'network',                  description: 'Website URL' },
      { name: 'merchant_type',     type: 'enum',    tag: 'network',                  description: 'POS / CNP / mPOS' },
      { name: 'registration_date', type: 'date',    tag: 'temporal',                 description: 'Date merchant joined network' },
      { name: 'acquirer_id',       type: 'varchar', tag: 'identifier',               description: 'FK → disc_acquirers' },
    ],
  },
  {
    id: 'disc_terminals',
    label: 'disc_terminals',
    description: 'Physical POS and ATM terminals on the Discover network',
    recordCount: 5000,
    fields: [
      { name: 'terminal_id',      type: 'varchar', tag: 'identifier',               description: 'TID — present in every network transaction' },
      { name: 'merchant_id',      type: 'varchar', tag: 'identifier',               description: 'FK → disc_merchants' },
      { name: 'terminal_type',    type: 'enum',    tag: 'network',                  description: 'POS / ATM / mPOS' },
      { name: 'device_serial',    type: 'varchar', tag: 'identifier', joinKey: true,description: 'Hardware serial — soft join to cap device_fingerprint' },
      { name: 'software_version', type: 'varchar', tag: 'network',                  description: 'Terminal firmware version' },
      { name: 'ip_address',       type: 'varchar', tag: 'network',    joinKey: true,description: 'Terminal IP — soft join to cap_transactions.ip_address' },
      { name: 'location_lat',     type: 'decimal', tag: 'network',                  description: 'GPS latitude' },
      { name: 'location_lon',     type: 'decimal', tag: 'network',                  description: 'GPS longitude' },
      { name: 'installation_date',type: 'date',    tag: 'temporal',                 description: 'Terminal installation date' },
    ],
  },
  {
    id: 'disc_network_txns',
    label: 'disc_network_txns',
    description: 'ALL transactions routed through Discover network — every issuer, not just Discover cardholders',
    recordCount: 100000,
    fields: [
      { name: 'network_txn_id',         type: 'varchar',   tag: 'identifier', joinKey: true,description: 'Primary key — joins to cap_transactions via auth_code' },
      { name: 'issuer_bin',             type: 'char(6)',   tag: 'identifier', joinKey: true,description: 'Identifies which bank issued the card — maps to disc_bin_table' },
      { name: 'issuer_id',              type: 'varchar',   tag: 'identifier',               description: 'Issuer institution identifier' },
      { name: 'merchant_id',            type: 'varchar',   tag: 'identifier',               description: 'FK → disc_merchants' },
      { name: 'terminal_id',            type: 'varchar',   tag: 'identifier',               description: 'FK → disc_terminals' },
      { name: 'acquirer_id',            type: 'varchar',   tag: 'identifier',               description: 'FK → disc_acquirers' },
      { name: 'pan_hash',               type: 'varchar',   tag: 'identifier', joinKey: true,description: 'PAN hash — hard join to cap_accounts.pan_hash' },
      { name: 'card_type',              type: 'enum',      tag: 'financial',  joinKey: true,description: '⚠ consumer / commercial — network classification, may differ from issuer truth' },
      { name: 'amount',                 type: 'decimal',   tag: 'financial',                description: 'Transaction amount' },
      { name: 'currency',               type: 'char(3)',   tag: 'financial',                description: 'ISO 4217 currency' },
      { name: 'interchange_rate_applied',type:'decimal',   tag: 'financial',                description: 'Rate applied — driven by card_type classification' },
      { name: 'interchange_fee_charged',type: 'decimal',   tag: 'financial',                description: 'Fee charged — impacted if card_type is wrong' },
      { name: 'auth_datetime',          type: 'timestamp', tag: 'temporal',                 description: 'Authorization time' },
      { name: 'clearing_datetime',      type: 'timestamp', tag: 'temporal',                 description: 'Clearing time' },
      { name: 'settlement_datetime',    type: 'timestamp', tag: 'temporal',                 description: 'Settlement time' },
      { name: 'auth_code',              type: 'varchar',   tag: 'identifier', joinKey: true,description: 'Auth code — hard join to cap_transactions.auth_code' },
      { name: 'entry_mode',             type: 'enum',      tag: 'network',                  description: 'swipe / chip / tap / CNP' },
      { name: 'network_fraud_score',    type: 'decimal',   tag: 'risk',                     description: 'Real-time network fraud score 0–1' },
    ],
  },
  {
    id: 'disc_settlements',
    label: 'disc_settlements',
    description: 'Daily settlement records per merchant — financial reconciliation',
    recordCount: 2000,
    fields: [
      { name: 'settlement_id',        type: 'varchar', tag: 'identifier',description: 'Primary key' },
      { name: 'merchant_id',          type: 'varchar', tag: 'identifier',description: 'FK → disc_merchants' },
      { name: 'acquirer_id',          type: 'varchar', tag: 'identifier',description: 'FK → disc_acquirers' },
      { name: 'settlement_date',      type: 'date',    tag: 'temporal',  description: 'Settlement date' },
      { name: 'gross_amount',         type: 'decimal', tag: 'financial', description: 'Total transaction volume' },
      { name: 'total_interchange',    type: 'decimal', tag: 'financial', description: 'Interchange fees collected' },
      { name: 'chargeback_count',     type: 'int',     tag: 'risk',      description: 'Number of chargebacks in period' },
      { name: 'disputed_amount',      type: 'decimal', tag: 'financial', description: 'Total disputed funds' },
      { name: 'net_settlement_amount',type: 'decimal', tag: 'financial', description: 'Net amount transferred to merchant' },
    ],
  },
  {
    id: 'disc_chargebacks',
    label: 'disc_chargebacks',
    description: 'Network-level chargeback records — visible across all issuers',
    recordCount: 1200,
    fields: [
      { name: 'chargeback_id',     type: 'varchar', tag: 'identifier', joinKey: true,description: 'Primary key — joins to cap_disputes on txn' },
      { name: 'network_txn_id',    type: 'varchar', tag: 'identifier', joinKey: true,description: 'FK → disc_network_txns' },
      { name: 'merchant_id',       type: 'varchar', tag: 'identifier',               description: 'FK → disc_merchants' },
      { name: 'issuer_bin',        type: 'char(6)', tag: 'identifier',               description: 'BIN of card that filed the chargeback' },
      { name: 'reason_code',       type: 'varchar', tag: 'risk',                     description: 'Dispute reason code' },
      { name: 'dispute_amount',    type: 'decimal', tag: 'financial',                description: 'Amount in dispute' },
      { name: 'filing_date',       type: 'date',    tag: 'temporal',                 description: 'Date chargeback filed' },
      { name: 'response_deadline', type: 'date',    tag: 'temporal',                 description: 'Merchant response deadline' },
      { name: 'resolution_status', type: 'enum',    tag: 'risk',                     description: 'open / won_issuer / won_merchant / arbitration' },
    ],
  },
  {
    id: 'disc_bin_table',
    label: 'disc_bin_table',
    description: 'BIN lookup table — maps 6-digit BINs to issuing banks',
    recordCount: 150,
    fields: [
      { name: 'bin',               type: 'char(6)', tag: 'identifier', joinKey: true,description: 'Bank Identification Number — joins cap_accounts.bin' },
      { name: 'issuer_id',         type: 'varchar', tag: 'identifier',               description: 'Issuer institution ID' },
      { name: 'issuer_name',       type: 'varchar', tag: 'identifier',               description: 'Issuer bank name' },
      { name: 'issuer_country',    type: 'char(2)', tag: 'identifier',               description: 'Issuer country code' },
      { name: 'card_type',         type: 'enum',    tag: 'financial',  joinKey: true,description: "consumer / commercial — Discover network's declared card type per BIN" },
      { name: 'card_brand',        type: 'varchar', tag: 'identifier',               description: 'Card network brand' },
      { name: 'card_product_tier', type: 'enum',    tag: 'financial',                description: 'standard / gold / platinum / signature / infinite' },
    ],
  },
  {
    id: 'disc_fraud_patterns',
    label: 'disc_fraud_patterns',
    description: 'Network-level fraud intelligence — cross-issuer patterns invisible to any single bank',
    recordCount: 80,
    fields: [
      { name: 'pattern_id',          type: 'varchar', tag: 'identifier',description: 'Primary key' },
      { name: 'pattern_type',        type: 'enum',    tag: 'risk',      description: 'ring / mule / synthetic / bust_out / laundering' },
      { name: 'merchant_ids',        type: 'array',   tag: 'identifier',description: 'Merchants involved in pattern' },
      { name: 'bin_ranges',          type: 'array',   tag: 'identifier',description: 'BIN ranges affected — may span multiple issuers' },
      { name: 'velocity_indicators', type: 'text',    tag: 'behavioral',description: 'Velocity pattern description' },
      { name: 'geographic_spread',   type: 'varchar', tag: 'behavioral',description: 'Geographic footprint of pattern' },
      { name: 'cross_issuer',        type: 'boolean', tag: 'risk',      description: '⚑ True = pattern spans multiple banks — only Discover can see this' },
      { name: 'first_observed',      type: 'date',    tag: 'temporal',  description: 'Pattern first detected' },
      { name: 'last_observed',       type: 'date',    tag: 'temporal',  description: 'Most recent activity' },
      { name: 'active',              type: 'boolean', tag: 'risk',      description: 'Currently active' },
    ],
  },
]

export const JOIN_KEYS: JoinKey[] = [
  // Hard joins
  {
    id: 'jk-auth-code',
    category: 'hard',
    leftTable: 'cap_transactions',
    leftField: 'auth_code',
    rightTable: 'disc_network_txns',
    rightField: 'auth_code',
    signal: 'Authorization code',
    confidence: 100,
    description: 'Same 6-char auth code appears on both the issuer authorization record and the network routing record — 1:1 deterministic join giving a 360° view of every transaction.',
  },
  {
    id: 'jk-pan-hash',
    category: 'hard',
    leftTable: 'cap_accounts',
    leftField: 'pan_hash',
    rightTable: 'disc_network_txns',
    rightField: 'pan_hash',
    signal: 'PAN hash',
    confidence: 100,
    description: 'SHA-256 of the card PAN is the same value on both sides — links every Cap One cardholder\'s account to their network transaction history.',
  },
  {
    id: 'jk-merchant-id',
    category: 'hard',
    leftTable: 'cap_transactions',
    leftField: 'merchant_id',
    rightTable: 'disc_merchants',
    rightField: 'merchant_id',
    signal: 'Merchant ID (MID)',
    confidence: 100,
    description: 'Discover assigns the MID and passes it back through the network to the issuer. Cap One receives it in the authorization message — deterministic merchant enrichment.',
  },
  {
    id: 'jk-bin',
    category: 'hard',
    leftTable: 'cap_accounts',
    leftField: 'bin',
    rightTable: 'disc_bin_table',
    rightField: 'bin',
    signal: 'Bank Identification Number',
    confidence: 100,
    description: 'BIN table maps every 6-digit card prefix to its issuer — links Cap One accounts to Discover\'s issuer registry and reveals card type classification.',
  },
  // Soft joins — ER signals
  {
    id: 'jk-ssn4',
    category: 'soft',
    leftTable: 'cap_customers',
    leftField: 'ssn_last4',
    rightTable: 'disc_customers',
    rightField: 'ssn_last4',
    signal: 'Last 4 SSN',
    confidence: 35,
    description: 'Highest-weight ER signal (35 pts). When last-4 SSN matches across both CRMs, combined with DOB match, probability of same person exceeds 99.5%.',
  },
  {
    id: 'jk-dob',
    category: 'soft',
    leftTable: 'cap_customers',
    leftField: 'dob',
    rightTable: 'disc_customers',
    rightField: 'dob',
    signal: 'Date of birth',
    confidence: 25,
    description: 'Second-highest ER signal (25 pts). Exact DOB match. Combined with name similarity pushes match confidence above threshold independently.',
  },
  {
    id: 'jk-name',
    category: 'soft',
    leftTable: 'cap_customers',
    leftField: 'name_hash',
    rightTable: 'disc_customers',
    rightField: 'name_hash',
    signal: 'Name — Jaro-Winkler fuzzy',
    confidence: 20,
    description: 'Normalized name scored with Jaro-Winkler similarity (20 pts max). Handles maiden name variants, hyphenated names, and minor transcription differences.',
  },
  {
    id: 'jk-address',
    category: 'soft',
    leftTable: 'cap_customers',
    leftField: 'address_billing',
    rightTable: 'disc_customers',
    rightField: 'address_billing',
    signal: 'Address — token overlap',
    confidence: 15,
    description: 'Address tokenized and scored on token overlap (15 pts max). Handles Apt vs Suite, abbreviated vs spelled-out street types, and postal normalization.',
  },
  {
    id: 'jk-phone',
    category: 'soft',
    leftTable: 'cap_customers',
    leftField: 'phone_primary',
    rightTable: 'disc_customers',
    rightField: 'phone_primary',
    signal: 'Phone number',
    confidence: 5,
    description: 'Exact phone match (5 pts bonus). High precision but lower recall — customers frequently have different phones on file at each institution.',
  },
  // Behavioral joins
  {
    id: 'jk-ip-address',
    category: 'behavioral',
    leftTable: 'cap_device_sessions',
    leftField: 'ip_address',
    rightTable: 'disc_terminals',
    rightField: 'ip_address',
    signal: 'Shared IP address',
    confidence: 80,
    description: 'Same IP appears in a Cap One customer session and a Discover merchant terminal. Indicates a customer device and a POS terminal are on the same network — strong fraud signal.',
  },
  {
    id: 'jk-device-fp',
    category: 'behavioral',
    leftTable: 'cap_device_sessions',
    leftField: 'device_fingerprint',
    rightTable: 'disc_terminals',
    rightField: 'device_serial',
    signal: 'Device fingerprint ↔ terminal serial',
    confidence: 90,
    description: 'Browser/device fingerprint matches a Discover terminal serial — a consumer device is acting as a merchant terminal. Strongest behavioral fraud signal.',
  },
  {
    id: 'jk-ein',
    category: 'behavioral',
    leftTable: 'cap_commercial',
    leftField: 'ein_hash',
    rightTable: 'disc_merchants',
    rightField: 'ein_hash',
    signal: 'EIN hash',
    confidence: 95,
    description: 'A Cap One commercial banking counterparty is the same legal entity as a Discover network merchant. Enables NBFI risk cross-check: credit exposure on one side, transaction behavior on the other.',
  },
  {
    id: 'jk-dispute-chargeback',
    category: 'behavioral',
    leftTable: 'cap_disputes',
    leftField: 'txn_id',
    rightTable: 'disc_chargebacks',
    rightField: 'network_txn_id',
    signal: 'Dispute ↔ chargeback',
    confidence: 85,
    description: 'A Cap One dispute and a Discover chargeback originate from the same underlying transaction — joining auth_code gives the complete dispute lifecycle from both issuer and network perspectives.',
  },
]
